import fs from "fs"
import path from 'path'
import matter from "gray-matter"

import React from 'react'
import Head from 'next/head'
import Link from "next/link"

import { Presentation } from "../component/presentation"

export default function Home({posts}) {
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {posts.map(({slug, frontmatter}, index) => (
          <section key={index}>
            <div>
              <Link href={`/blog/${slug}`}><a>{frontmatter.title}</a></Link>
              <div>{frontmatter.date}</div>
            </div>
            <div>{frontmatter.keyFilter}</div>
            <div>{frontmatter.spoiler}</div>
            
          </section>
        ))}
      </main>
      
    </div>
  )
}

export async function getStaticProps(){
  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map(fileName => {
    const slug = fileName.replace('.md', '')

    const markdownWithMeta = fs.readFileSync(
      path.join('posts', fileName)
    )

    const {data: frontmatter } = matter(markdownWithMeta)

    return{
      slug,
      frontmatter
    }
  })

  return{
    props: {
      posts: posts 
    }
  }
  
}